### ISSUE TITLE
feel free to create a pull request to fix

### ISSUE THREAD

**Issue by hanxinhao000** [khanhduytran0/exagear_windows_emulator#1]
What should I do?

**Comment by khanhduytran0** [comment]
Do anything can fix.

**Comment by hanxinhao000** [comment]
what?Can you be more specific? Thank you for the.I'm going to launch the exit

**Comment by hanxinhao000** [comment]
启动直接就退出了（闪退。。。）

**Comment by hanxinhao000** [comment]
2020-04-16 15:52:40.626 13515-13854/com.eltechs.ed E/AndroidRuntime: FATAL EXCEPTION: Thread-57
    Process: com.eltechs.ed, PID: 13515
    java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:126)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:434)
        at com.eltechs.axs.xserver.impl.LocksManagerImpl$MultiXLock.close(LocksManagerImpl.java:29)
        at com.eltechs.axs.xserver.client.XClient.freeAssociatedResources(XClient.java:229)
        at com.eltechs.axs.xserver.client.XClientConnectionHandler.handleConnectionShutdown(XClientConnectionHandler.java:20)
        at com.eltechs.axs.xserver.client.XClientConnectionHandler.handleConnectionShutdown(XClientConnectionHandler.java:8)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.killConnection(EpollProcessorThread.java:262)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.processHangup(EpollProcessorThread.java:270)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.processClientMessage(EpollProcessorThread.java:202)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.doEpoll(Native Method)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.epollIndefinitely(EpollProcessorThread.java:282)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.runOnce(EpollProcessorThread.java:162)
        at com.eltechs.axs.xconnectors.epoll.impl.EpollProcessorThread.run(EpollProcessorThread.java:144)

**Comment by hanxinhao000** [comment]
The sidebar - >Manage Conta.. ->Run Explorer

**Comment by khanhduytran0** [comment]
Yep, I'm Unable to fix crashes, that is decompiled code.

**Comment by hanxinhao000** [comment]
3q,next go see
